import Header from "@/src/Header";
import Introduce from "@/src/Introduce";
import { css } from "@emotion/react";
import Head from "next/head";

const containerStyle = () => css`
  max-width: 1024px;
  margin: 0 auto;
  padding: 0 20px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={containerStyle}>
        <Header />
        <Introduce />
      </main>
    </>
  );
}
